#!/bin/sh -ue
#
# Taken from https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/linux-setup.html
#

AR=archive
DEPENDENCIES="gcc git wget make libncurses-dev flex bison gperf python virtualenv"
ESP_VERSION=3.1.2
ESP_ARCHIVE=ESP8266_RTOS_SDK-$ESP_VERSION.tar.gz
GCC_ARCHIVE=GCC_xtensa-lx106_1.22.0_amd64.tar.gz
SETUP_FILE=setup_env

mkdir -p $AR

if [ ! -d esp/xtensa-lx106-elf ] ; then
	if [ ! -e $AR/$GCC_ARCHIVE ] ; then
		echo "Downloading $GCC_ARCHIVE"
		curl https://dl.espressif.com/dl/xtensa-lx106-elf-linux64-1.22.0-100-ge567ec7-5.2.0.tar.gz > $AR/$GCC_ARCHIVE
	fi

	echo "Extracting $GCC_ARCHIVE"
	mkdir -p esp
	tar -C esp -xzf $AR/$GCC_ARCHIVE
fi

if [ ! -d sdk/ESP8266_RTOS_SDK-$ESP_VERSION ] ; then
	if [ ! -e $AR/$ESP_ARCHIVE ] ; then
		echo "Downloading $ESP_ARCHIVE"
		# Redirection from https://github.com/espressif/ESP8266_RTOS_SDK/archive/v$ESP_VERSION.tar.gz
		curl https://codeload.github.com/espressif/ESP8266_RTOS_SDK/tar.gz/v$ESP_VERSION > $AR/$ESP_ARCHIVE
	fi

	echo "Extracting $ESP_ARCHIVE"
	mkdir -p sdk
	tar -C sdk -xzf $AR/$ESP_ARCHIVE
fi

if ! groups | grep -q dialout ; then
	echo "Adding user $USER to group dialout.."
	sudo usermod -a -G dialout $USER
	echo "Making changes to groups active.."
	sudo su $USER
fi

for DEP in $DEPENDENCIES ; do
	if [ ! -e .stamp_installed_$DEP ] ; then
		echo "Installing dependency $DEP.."
		sudo apt-get -y install $DEP
		touch .stamp_installed_$DEP
	fi
done

if [ ! -d pyEnv ] ; then
	echo "Creating python virtual environment.."
	virtualenv $(pwd)/pyEnv -p python2.7
	. $(pwd)/pyEnv/bin/activate
	pip install pyserial
	pip install -r sdk/ESP8266_RTOS_SDK-$ESP_VERSION/docs/requirements.txt
	deactivate
fi



if [ ! -e  $SETUP_FILE ] ; then
	echo "Creating setup file.."
	cat <<EOF >>$SETUP_FILE
#!/to/be/sourced!
#
# This shell script sets the environment variables. It is intended to be sourced.
#
# Do not edit this file. It was automatically created by $0 ($(date '+%y/%m/%d %H:%M'))
#
export SDK_PATH=$(pwd)/sdk/ESP8266_RTOS_SDK-${ESP_VERSION}
export IDF_PATH=$(pwd)/sdk/ESP8266_RTOS_SDK-${ESP_VERSION}
export BIN_PATH=$(pwd)/output

# Active virtual environment
source $(pwd)/pyEnv/bin/activate
echo "Leave the python virtual environment by typing 'deativate'"

# GCC compiler
export PATH=\$PATH:$(pwd)/esp/xtensa-lx106-elf/bin/
# Python PIP installation
export PATH=\$PATH:$HOME/.local/bin
EOF
fi

echo
echo "Setup completed successfully. Source $SETUP_FILE with '. $SETUP_FILE'..."
echo
